### ISSUE TITLE
Support `--select-1` and `--exit-0` from fzf

### ISSUE THREAD

**Issue by DUOLabs333** [andreax79/pzp#1]

**Comment by andreax79** [comment]
From fzf manual page:

      -1, --select-1
              If there is only one match for the initial query (--query), do not start interactive finder and automatically select the only match

      -0, --exit-0
              If there is no match for the initial query (--query), do not start interactive finder and exit immediately

**Comment by andreax79** [comment]
Lazy option added in v0.0.15
https://pzp.readthedocs.io/en/latest/api/module/#pzp.pzp

**Comment by DUOLabs333** [comment]
Awesome, thanks.

**Comment by DUOLabs333** [comment]
Just a follow-up question: is there a way to tell if pzp didn't find anything (either through lazy mode or the user pressed <Enter> on an empty list) or the user aborted? Looking through the docs, it could probably be done through pzp.exceptions somehow, but I'm not sure.

**Comment by andreax79** [comment]
yes, you can change the action binded to the enter key like the following example:

    try:
        item = pzp(
            candidates=...
            keys_binding={"custom-accept": ["enter"]},
        )
        print(item)
    except CustomAction as action:
        print(f"action: {action.action} selected item: {action.selected_item}")

**Comment by DUOLabs333** [comment]
I tried `except pzp.exceptions.AbortAction`, but it did not work.

**Comment by DUOLabs333** [comment]
Oh, `pzp` doesn't expose that (probably for the best in most cases). Hmmm... not sure what the best way to support that should be.

However, lazy mode doesn't work completely like expected --- even if there's no selections that match input, it still shows a finder, instead of just exiting. To support this I think this would have to be implemented in finder.py itself.

**Comment by andreax79** [comment]
For the lazy mode, I tested the following cases and the finder is not shown.
```console
$ python3 -c 'from pzp import pzp; print(pzp([1], lazy=True))'
1
$ python3 -c 'from pzp import pzp; print(pzp([], lazy=True))'
None
```

**Comment by DUOLabs333** [comment]
I mean that something like `pzp(['foo','bar','baz'],input='btm',lazy=True)` should raise some exception saying that nothing was found.

**Comment by andreax79** [comment]
Ok, fixed in the new version v0.0.16. Now your example with `input` work as expected.
I added an example file `examples/number_selector.py` exposing the exceptions.

**Comment by DUOLabs333** [comment]
This still doesn't do what I expected --- if no selection is found, it just returns None.

**Comment by andreax79** [comment]
```console
./examples/number_selector.sh --input x --lazy
action: lazy-accept selected item: None
```
It raises an exception.

**Comment by DUOLabs333** [comment]
Oh, you have to deal with finder directly. Is there a way to expose this to the `pzp` function itself?

**Comment by andreax79** [comment]
Option `handle_actions` added. The following example raises exceptions: 
```python
pzp(["a", "b", "c"], input="d", lazy=True, handle_actions=None) 
```

**Comment by DUOLabs333** [comment]
Awesome --- it works perfectly.
